version: "2.1"

services:

  cli:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: cli
    environment:
      - LC_ALL=en_US.UTF-8
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US.UTF-8
      - VIRTUAL_HOST
      - TERMINUS_SITE
      - TERMINUS_ENVIRONMENT
    volumes:
      - ${PROJECT_ROOT}/.docksal/etc/drush:/etc/drush:ro

  # Mailhog
  mail:
    hostname: mail
    image: mailhog/mailhog
    expose:
      - "80"
    environment:
      - MH_API_BIND_ADDR=0.0.0.0:80
      - MH_UI_BIND_ADDR=0.0.0.0:80
    labels:
      - io.docksal.virtual-host=webmail.${VIRTUAL_HOST}
    user: root

  # Behat
  behat:
    hostname: behat
    image: docksal/behat
    volumes:
      - ${PROJECT_ROOT}/tests/behat:/src
    # Keep the container running
    entrypoint: "top -b"