access_ui: 1.4.0-beta1
block: 8.6.9
breakpoint: 8.6.9
ckeditor: 8.6.9
config: 8.6.9
consumers: 1.9.0
content_model_ui: 1.4.0-beta1
content_moderation: 8.6.9
crop: 2.0.0-rc1
ctools: 3.1.0
datetime: 8.6.9
dblog: 8.6.9
diff: 1.0.0-rc2
dropzonejs: 2.0.0-alpha3
editor: 8.6.9
embed: 1.0.0
entity_block: 1.0.0-beta1
entity_browser: 2.0.0
entity_embed: 1.0.0-beta2
entity_reference: 8.6.9
field: 8.6.9
field_ui: 8.6.9
file: 8.6.9
filter: 8.6.9
headless_ui: 1.4.0-beta1
help: 8.6.9
image: 8.6.9
image_widget_crop: 2.2.0
inline_entity_form: 1.0.0-rc1
json_content: 1.4.0-beta1
jsonapi: 2.1.0
layout_discovery: 8.6.9
lightning: 3.204.0
lightning_core: 3.5.0
lightning_install: 3.204.0
link: 8.6.9
media: 8.6.9
media_library: 8.6.9
node: 8.6.9
options: 8.6.9
page_cache: 8.6.9
path: 8.6.9
serialization: 8.6.9
shortcut: 8.6.9
system: 8.6.9
taxonomy: 8.6.9
text: 8.6.9
token: 1.5.0
toolbar: 8.6.9
user: 8.6.9
workflows: 8.6.9
menu_link_content: 8.6.9
views: 8.6.9
schemata: 1.0.0-alpha5
schemata_json_schema: 1.0.0-alpha5
openapi: 1.0.0-beta2
openapi_ui: 1.0.0-rc1
openapi_ui_redoc: 1.0.0-rc2
openapi_ui_swagger: 1.0.0-rc3
simple_oauth: 3.14.0
simple_oauth_extras: 3.14.0
lightning_api: 3.2.0
lightning_page: 3.5.0
lightning_roles: 3.5.0
panels: 4.3.0
views_infinite_scroll: 1.5.0
lightning_media: 3.5.0
lightning_media_audio: 3.5.0
lightning_media_bulk_upload: 3.5.0
lightning_media_document: 3.5.0
lightning_media_image: 3.5.0
media_entity_instagram: 2.0.0-alpha2
lightning_media_instagram: 3.5.0
media_entity_twitter: 2.0.0-alpha2
lightning_media_twitter: 3.5.0
video_embed_field: 2.0.0
video_embed_media: 2.0.0
lightning_media_video: 3.5.0
lightning_workflow: 3.3.0
lightning_scheduler: 3.3.0
page_manager: 4.0.0-beta3
moderation_dashboard: 1.0.0-beta1
moderation_sidebar: 1.1.0
pathauto: 1.3.0
headless_lightning: 1.4.0-beta1
update: 8.6.9
config_direct_save: 1.0.0
simple_block: 1.0.0-beta1
